name: dapsl
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - jupyter
  - pip
  - pip:
    - botorch
    - gpytorch
    - pymoo==0.5.0
    - pymop
    - deap
    - optuna
    - tqdm
    - joblib
    - openpyxl